name: Greeting on variable day

on: push

env:
  day-of-week: Monday

jobs:
  greeting_job:
    runs-on: Ubuntu-latest
    env:
      greeting: Hello
    steps:
      - name: "Say hello Deva Its Monday"
        run: echo "$greeting $first_name today is $day-of-week"
        env:
          first_name: Deva
